// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/JoubertNatividade/FutClub/main/domain/commands"
	"github.com/JoubertNatividade/FutClub/main/infrastructure/controllers"
	"github.com/JoubertNatividade/FutClub/main/infrastructure/repositories"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func initializeApp() *App {
	db := ConnectionMySQL()
	playerRepository := repositories.NewPlayerRepository(db)
	playerCommand := commands.NewPlayerCommand(playerRepository)
	playerController := controllers.NewPlayerController(playerCommand)
	app := NewApp(playerController)
	return app
}
