
CREATE DATABASE IF NOT EXISTS season (
	season_id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE DATABASE IF NOT EXISTS player (
	player_id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	position VARCHAR(50),
	url_avatar VARCHAR(255),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE DATABASE IF NOT EXISTS podium (
	podium_id INT AUTO_INCREMENT PRIMARY KEY,
	season_id INT NOT NULL,
	player_id INT NOT NULL,
	classification INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (season_id) REFERENCES season(season_id) ON DELETE CASCADE,
	FOREIGN KEY (player_id) REFERENCES player(player_id) ON DELETE CASCADE
)

CREATE DATABASE IF NOT EXISTS round (
	round_id INT AUTO_INCREMENT PRIMARY KEY,
	round_date DATE NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE DATABASE IF NOT EXISTS player_round_status (
	id INT AUTO_INCREMENT PRIMARY KEY,
	player_id INT NOT NULL,
	round_id INT NOT NULL,
	gol INT DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (player_id) REFERENCES player(player_id) ON DELETE CASCADE,
	FOREIGN KEY (round_id) REFERENCES round(round_id) ON DELETE CASCADE
);
