
CREATE TABLE player (
	player_id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	position VARCHAR(50),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE round (
	round_id INT AUTO_INCREMENT PRIMARY KEY,
	round_date DATE NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE player_round_gol (
	id INT AUTO_INCREMENT PRIMARY KEY,
	player_id INT NOT NULL,
	round_id INT NOT NULL,
	gol INT DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (player_id) REFERENCES player(player_id) ON DELETE CASCADE,
	FOREIGN KEY (round_id) REFERENCES round(round_id) ON DELETE CASCADE
);
